/*
 * MioLink revision B - Pico SDK board header.
 */
#ifndef _BOARDS_OVERLAY_MIOLINK_REV_B_OVERLAY_H
#define _BOARDS_OVERLAY_MIOLINK_REV_B_OVERLAY_H

/* --- MioLink rev B: target voltage / power --- */
#define MIOLINK_REVB_TARGET_VOLTAGE_ADC_CHANNEL 3
#define MIOLINK_REVB_TARGET_VOLTAGE_ENABLE_PIN  3
#define MIOLINK_REVB_TARGET_VOLTAGE_FAULT_PIN  1

/* --- MioLink rev B: LEDs --- */
#define MIOLINK_REVB_LED_ACT_PIN 13
#define MIOLINK_REVB_LED_ERR_PIN 10
#define MIOLINK_REVB_LED_SER_PIN 12

/* --- MioLink rev B: JTAG/SWD --- */
#define MIOLINK_REVB_TARGET_TCK_PIN     24
#define MIOLINK_REVB_TARGET_TDO_PIN     17
#define MIOLINK_REVB_TARGET_TDI_PIN     28
#define MIOLINK_REVB_TARGET_TMS_PIN     26
#define MIOLINK_REVB_TARGET_TMS_DIR_PIN 25

/* --- MioLink rev B: UART --- */
#define MIOLINK_REVB_TARGET_UART_TX_PIN 8
#define MIOLINK_REVB_TARGET_UART_RX_PIN 21

/* --- MioLink rev B: Reset --- */
#define MIOLINK_REVB_TARGET_NRST_PIN 18

#endif /* _BOARDS_OVERLAY_MIOLINK_REV_B_OVERLAY_H */
